name: Build binary

on: workflow_dispatch
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --profile opt --target x86_64-unknown-linux-musl --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        path: 'target/opt/iced_example'
