name: Build binary

on: workflow_dispatch
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install CMake
      uses: lukka/get-cmake@latest
    - name: Print CMake version
      run: cmake --version
    - name: Build musl static binary
      uses: gmiam/rust-musl-action@master
      with:
        args: cargo build --profile opt --target x86_64-unknown-linux-musl --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        path: 'target/x86_64-unknown-linux-musl/opt/iced_example'
